language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
before_script:
  - psql -c 'create database learning-journal;' -U mark
# command to run tests
script: lettuce