language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
# command to run tests
script: py.test test_journal_orm.py